# Generated by Django 5.2.5 on 2025-08-20 12:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_add_voter_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='assets_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='criminal_cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='manifesto',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='verification_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='customuser',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lock_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='backup_servers',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='election',
            name='block_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='election',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='election',
            name='consensus_status',
            field=models.CharField(choices=[('pending', 'Pending Consensus'), ('achieved', 'Consensus Achieved'), ('failed', 'Consensus Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='election',
            name='district',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='election',
            name='merkle_root',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='election',
            name='ntp_server',
            field=models.CharField(default='pool.ntp.org', max_length=100),
        ),
        migrations.AddField(
            model_name='election',
            name='previous_block_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='election',
            name='primary_server',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='election',
            name='replication_factor',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='election',
            name='synchronized_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='synchronized_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='backup_nodes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='vote',
            name='confirmation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vote',
            name='encrypted_vote_data',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='is_replicated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vote',
            name='node_confirmations',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='vote',
            name='nonce',
            field=models.CharField(default='00000000000000000000000000000000', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='previous_vote_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='vote',
            name='required_confirmations',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='vote',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('consensus_pending', 'Awaiting Consensus'), ('finalized', 'Finalized')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_hash',
            field=models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='assembly_constituency',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='voter',
            name='constituency',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='voter',
            name='district',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='voter',
            name='face_encoding',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='face_recognition_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voter',
            name='parliamentary_constituency',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='party',
            field=models.CharField(choices=[('BJP', 'BJP'), ('Congress', 'Congress'), ('AAP', 'AAP'), ('Left Front', 'Left Front'), ('BSP', 'BSP'), ('SP', 'SP'), ('TMC', 'TMC'), ('JDU', 'JDU'), ('RJD', 'RJD'), ('Independent', 'Independent'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('voter', 'Voter'), ('admin', 'Admin'), ('observer', 'Observer')], default='voter', max_length=10),
        ),
        migrations.AlterField(
            model_name='election',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='election',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('suspended', 'Suspended')], default='upcoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='vote',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_type', models.CharField(choices=[('vote_cast', 'Vote Cast'), ('vote_verified', 'Vote Verified'), ('consensus_achieved', 'Consensus Achieved'), ('node_failure', 'Node Failure'), ('election_started', 'Election Started'), ('election_ended', 'Election Ended'), ('admin_action', 'Admin Action'), ('security_event', 'Security Event')], max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('hash_chain', models.CharField(max_length=64)),
                ('previous_hash', models.CharField(blank=True, max_length=64)),
                ('election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voting.election')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ElectionNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('faulty', 'Faulty'), ('byzantine', 'Byzantine Fault')], default='active', max_length=20)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('response_time', models.FloatField(default=0.0)),
                ('uptime_percentage', models.FloatField(default=100.0)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='voting.election')),
            ],
        ),
        migrations.CreateModel(
            name='VoterSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=128, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=128)),
                ('location_hash', models.CharField(blank=True, max_length=64)),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.voter')),
            ],
        ),
        migrations.CreateModel(
            name='VoteConsensusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=100)),
                ('consensus_round', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('signature', models.TextField()),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consensus_logs', to='voting.vote')),
            ],
            options={
                'unique_together': {('vote', 'node_id', 'consensus_round')},
            },
        ),
    ]
