# Generated by Django 5.2.5 on 2025-10-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_candidate_age_candidate_assets_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='consensus_threshold',
            field=models.IntegerField(choices=[(51, '51% (Simple Majority)'), (67, '67% (Super Majority)'), (75, '75% (High Consensus)')], default=51),
        ),
    ]
