# Generated by Django 5.2.5 on 2025-10-09 02:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_convert_election_to_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=10)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='voter',
            name='aadhar_document',
            field=models.FileField(blank=True, help_text='Upload Aadhar Card (PDF/Image)', null=True, upload_to='voter_documents/aadhar/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='voter',
            name='pan_document',
            field=models.FileField(blank=True, help_text='Upload PAN Card (PDF/Image)', null=True, upload_to='voter_documents/pan/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='voter',
            name='voter_id_document',
            field=models.FileField(blank=True, help_text='Upload Voter ID Card (PDF/Image)', null=True, upload_to='voter_documents/voter_id/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
