# Generated by Django 5.2.5 on 2025-10-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_otpverification_voter_aadhar_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
