# Generated by Django 5.2.5 on 2025-12-14 16:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_otpverification_email_alter_otpverification_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('voter', 'Voter'), ('admin', 'Admin'), ('observer', 'Observer'), ('candidate', 'Candidate')], default='voter', max_length=10),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voter_id_document',
            field=models.FileField(blank=True, help_text='Upload Voter ID Card- Optional (PDF/Image)', null=True, upload_to='voter_documents/voter_id/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.CreateModel(
            name='CandidateUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$')])),
                ('date_of_birth', models.DateField()),
                ('party', models.CharField(choices=[('BJP', 'BJP'), ('Congress', 'Congress'), ('AAP', 'AAP'), ('Left Front', 'Left Front'), ('BSP', 'BSP'), ('SP', 'SP'), ('TMC', 'TMC'), ('JDU', 'JDU'), ('RJD', 'RJD'), ('Independent', 'Independent'), ('Other', 'Other')], max_length=50)),
                ('constituency', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=50)),
                ('education', models.CharField(blank=True, max_length=200)),
                ('manifesto', models.TextField(blank=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('criminal_cases', models.IntegerField(default=0)),
                ('assets_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('street_address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('photo', models.FileField(blank=True, null=True, upload_to='candidate_documents/photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('aadhar_document', models.FileField(blank=True, null=True, upload_to='candidate_documents/aadhar/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('education_certificate', models.FileField(blank=True, null=True, upload_to='candidate_documents/education/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('affidavit', models.FileField(blank=True, null=True, upload_to='candidate_documents/affidavit/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('approval_status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_candidates', to=settings.AUTH_USER_MODEL)),
                ('linked_candidate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_user', to='voting.candidate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
