# Generated by Django 5.2.5 on 2025-12-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_alter_customuser_role_alter_voter_voter_id_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateuser',
            name='age',
        ),
        migrations.AlterField(
            model_name='candidateuser',
            name='candidate_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
